diff --git a/Makefile b/Makefile
new file mode 100644
index 0000000..f09addf
--- /dev/null
+++ b/Makefile
@@ -0,0 +1,30 @@
+all: qemu/make_run
+
+qemu/make_run: qemu/configure_done
+	# verbose -> add V=1
+	cd qemu && make -j$(shell grep -c ^processor /proc/cpuinfo)
+
+qemu/configure_done: Makefile
+	cd qemu && \
+	./configure --prefix=/ \
+	            --host=x86_64-pc-elf \
+	            --target-list=i386-softmmu,x86_64-softmmu,arm-softmmu,aarch64-softmmu \
+	            --without-default-features \
+	            --disable-werror \
+	            --disable-pie \
+	            --extra-cflags="${CFLAGS}" \
+	            --extra-cflags=-D__FreeBSD__ \
+	            --extra-cflags=-DG_DIR_SEPARATOR_S=\"/\" \
+	            --extra-cflags=-DG_SEARCHPATH_SEPARATOR_S=\":\" \
+	            --extra-cflags=-DGLIB_CHARSETALIAS_DIR=\"/\" \
+	            --extra-cflags=-Wno-suggest-attribute=format \
+	            --extra-cxxflags="${CXXFLAGS}" \
+	            --extra-ldflags="${LDFLAGS}" \
+	            --extra-ldflags="-Wl,--no-as-needed" \
+	            --extra-ldflags="${LDLIBS}" \
+	            --cross-prefix=${CROSS_DEV_PREFIX} \
+	&& \
+	touch configure_done
+
+.phony: qemu/make_run
+.NOTPARALLEL: qemu/make_run qemu/configure_done
